export const Env = {
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',

  DEFAULT_REDIRECT: 'DEFAULT_REDIRECT',

  SHORT_THROTTLE: 'SHORT_THROTTLE',
  MEDIUM_THROTTLE: 'MEDIUM_THROTTLE',
  LONG_THROTTLE: 'LONG_THROTTLE',

  PASSWORD_SALT: 'PASSWORD_SALT',
  JWT_SECRET: 'JWT_SECRET',
  JWT_TTL: 'JWT_TTL',
}

export const Events = {
  URL_CLICKED: 'url.visited',
}
